# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.106.2"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

desc "Run all tests and push to git"
  lane :git do
    gradle(task: "test")
    push_to_git_remote
  end

desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    # Run tests
    gradle(task: "test")
    # Push to git
    git tag beta
    push_to_git_remote

    gradle(
      task: 'assemble',
      build_type: 'Release',
    # Get the last version code and increment it.
      properties: {
        'versionCode' => versionCode + 1,
        'versionName' => versionName
      })
    crashlytics

  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    print "Completed lane actions"
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
    print "Lane actions failed"
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
